version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Wq8$zLp3!vRt7
      POSTGRES_DB: doneplay
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./apps/api/doneplay
    env_file:
      - ./apps/api/doneplay/.env.production
    depends_on:
      - db
    ports:
      - "4000:4000"

  web:
    build: ./apps/web/doneplay
    env_file:
      - ./apps/web/doneplay/.env.production
    depends_on:
      - api
    ports:
      - "3000:3000"

volumes:
  pgdata:
