services:
  db:
    image: postgres:16
    env_file:
      - ./.env.db
    ports:
      - "5433:5432" # host:container (changed host port to avoid conflict with xray on 5432)
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build:
      context: .
      target: api
    env_file:
      - ./apps/api/doneplay/.env.production
    depends_on:
      - db
    # Auto-run migrations before starting prod server (idempotent)
    command: ["pnpm", "--filter", "@doneplay/api", "start:prod:migrated"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:4000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s

  web:
    build:
      context: .
      target: web
    env_file:
      - ./apps/web/doneplay/.env.production
    depends_on:
      - api
    # After DNS + nginx verified, you can remove the ports above to make web internal-only.
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:3000"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 20s

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - web
      - api
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost/nginx-health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  pgdata:
