services:
  db:
    image: postgres:16
    env_file:
      - ./.env.db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      target: api
    env_file:
      - ./apps/api/doneplay/.env.production
    depends_on:
      - db
    ports:
      - "4000:4000"

  web:
    build:
      context: .
      target: web
    env_file:
      - ./apps/web/doneplay/.env.production
    depends_on:
      - api
    ports:
      - "3000:3000"

volumes:
  pgdata:
