# This file is generated by GitHub Copilot
# Excel file with multiple sheets for school management
# Use Python and openpyxl to generate the file

import openpyxl
from openpyxl import Workbook

wb = Workbook()

# Sheet 1: StudentList
ws1 = wb.active
ws1.title = "StudentList"
ws1.append(["StudentID", "FirstName", "LastName", "BirthDate", "Class", "ParentPhone"])
ws1.append(["1001", "Ali", "Ahmadi", "2012-05-10", "5A", "09121234567"])
ws1.append(["1002", "Sara", "Mohammadi", "2011-11-22", "5A", "09129876543"])

# Sheet 2: MathSkills
ws2 = wb.create_sheet(title="MathSkills")
ws2.append(["StudentID", "FirstName", "Addition/Subtraction", "Multiplication/Division", "ProblemSolving", "Notes"])
ws2.append(["1001", "Ali", "Good", "Average", "Excellent", "-"])
ws2.append(["1002", "Sara", "Excellent", "Good", "Good", "Needs practice in division"])

# Sheet 3: Attendance
ws3 = wb.create_sheet(title="Attendance")
ws3.append(["StudentID", "FirstName", "Date", "Status"])
ws3.append(["1001", "Ali", "2025-08-21", "Present"])
ws3.append(["1002", "Sara", "2025-08-21", "Absent"])

# Sheet 4: Behavior
ws4 = wb.create_sheet(title="Behavior")
ws4.append(["StudentID", "FirstName", "Date", "BehaviorNotes"])
ws4.append(["1001", "Ali", "2025-08-21", "Participated well in class"])
ws4.append(["1002", "Sara", "2025-08-21", "Needs to focus more"])

wb.save("school_template.xlsx")
print("Excel file 'school_template.xlsx' created successfully.")
